import { Sequelize } from "sequelize"
import { DataType } from "sequelize-typescript";
import { Produto } from "./Produto";
import { db } from "@/database/dbConnect";

const initProduto = (sequelizeInstance: Sequelize) => {
    Produto.init({
        id: { type: DataType.NUMBER, primaryKey: true },
        barras: { type: DataType.STRING },
        descricao: { type: DataType.STRING },
        unidade: { type: DataType.STRING },
        grupo: { type: DataType.NUMBER },
        fabricante: { type: DataType.NUMBER },
        referencia: { type: DataType.STRING },
        vlrCusto: { type: DataType.NUMBER },
        margemVista: { type: DataType.NUMBER },
        vlrVista: { type: DataType.NUMBER },
        margemPrazo: { type: DataType.NUMBER },
        vlrPrazo: { type: DataType.NUMBER },
        ncm: { type: DataType.STRING },
        cfopEntradaEstado: { type: DataType.STRING },
        cfopEntradaForaEstado: { type: DataType.STRING },
        cfopSaidaEstado: { type: DataType.STRING },
        cfopSaidaForaEstado: { type: DataType.STRING },
        cst: { type: DataType.STRING },
        percentualIcms: { type: DataType.NUMBER },
        idBalanca: { type: DataType.NUMBER },
        validadeBalanca: { type: DataType.NUMBER },
        idBaixaAlternativa: { type: DataType.NUMBER },
        qtdeBaixaAlternativa: { type: DataType.NUMBER },
        status: { type: DataType.NUMBER },
        dtAlteracao: { type: DataType.DATE },
        idUsuario: { type: DataType.NUMBER },
        vlrAtacado: { type: DataType.NUMBER },
        estoque: { type: DataType.NUMBER },
        percentualIcmsSt: { type: DataType.NUMBER },
        materiaPrima: { type: DataType.NUMBER },
        minimo: { type: DataType.NUMBER },
        maximo: { type: DataType.NUMBER },
        idFornecedor1: { type: DataType.NUMBER },
        idFornecedor2: { type: DataType.NUMBER },
        disponivelEntrega: { type: DataType.NUMBER },
        vlrOferta: { type: DataType.NUMBER },
        dtInicioOferta: { type: DataType.DATE },
        dtFimOferta: { type: DataType.DATE },
        idPlanoContas: { type: DataType.NUMBER },
        qtdeEmbalagemCompra: { type: DataType.NUMBER },
        barrasAdicional1: { type: DataType.STRING },
        barrasAdicional2: { type: DataType.STRING },
        vlrGelado: { type: DataType.NUMBER },
        qtdePromocional: { type: DataType.NUMBER },
        vlrQtdePromocional: { type: DataType.NUMBER },
        vlrCxNatural: { type: DataType.NUMBER },
        vlrCxGelado: { type: DataType.NUMBER },
        qtdeCx: { type: DataType.NUMBER },
        vlrPrazo2: { type: DataType.NUMBER },
        vlrPrazo3: { type: DataType.NUMBER },
        vlrPrazo4: { type: DataType.NUMBER },
        vlrPrazo5: { type: DataType.NUMBER },
        margemVlrPrazo2: { type: DataType.NUMBER },
        margemVlrPrazo3: { type: DataType.NUMBER },
        margemVlrPrazo4: { type: DataType.NUMBER },
        margemVlrPrazo5: { type: DataType.NUMBER },
        idSubGrupo: { type: DataType.NUMBER },
        localizacao: { type: DataType.STRING },
        idFamiliaProdutos: { type: DataType.NUMBER },
        img: { type: DataType.STRING },
        pisCstSaida: { type: DataType.STRING },
        pisCstEntrada: { type: DataType.STRING },
        pisAliqSaida: { type: DataType.NUMBER },
        cofinsCstSaida: { type: DataType.STRING },
        cofinsCstEntrada: { type: DataType.STRING },
        cofinsAliqSaida: { type: DataType.NUMBER },
        siglaIcms: { type: DataType.STRING },
        obs: { type: DataType.STRING },
        composicao: { type: DataType.STRING },
        medida: { type: DataType.STRING },
        pesoEmbalagem: { type: DataType.NUMBER },
        qtdeEmbalagemEtiqueta: { type: DataType.STRING },
        ulFornecedor: { type: DataType.STRING },
        ulCusto: { type: DataType.NUMBER },
        ulCompra: { type: DataType.DATE },
        estoque2: { type: DataType.NUMBER },
        idImpressora: { type: DataType.NUMBER },
        exibeApp: { type: DataType.NUMBER },
        adicionais: { type: DataType.NUMBER },
        qtdeAd: { type: DataType.NUMBER },
        aplicacao: { type: DataType.STRING },
        percComissao: { type: DataType.NUMBER },
        vlrFrete: { type: DataType.NUMBER },
        percReducIcms: { type: DataType.NUMBER },
        baseLegal: { type: DataType.STRING },
        icmsOrig: { type: DataType.STRING },
        cest: { type: DataType.STRING },
    }, {
        freezeTableName: true,
        sequelize: sequelizeInstance,
        modelName: "Produto",
        tableName: "produtos"
    })

    return { Produto }
}

export default initProduto(db).Produto