import { Model, Optional } from "sequelize"

export type AtributosProduto = {
    id: number;
	barras: string;
	descricao: string;
	unidade: string;
	grupo: number;
	fabricante: number;
	referencia: string;
	vlrCusto: number;
	margemVista: number;
	vlrVista: number;
	margemPrazo: number;
	vlrPrazo: number;
	ncm: string;
	cfopEntradaEstado: string;
	cfopEntradaForaEstado: string;
	cfopSaidaEstado: string;
	cfopSaidaForaEstado: string;
	cst: string;
	percentualIcms: number;
	idBalanca: number;
	validadeBalanca: number;
	idBaixaAlternativa: number;
	qtdeBaixaAlternativa: number;
	status: number;
	dtAlteracao: Date;
	idUsuario: number;
	vlrAtacado: number;
	estoque: number;
	percentualIcmsSt: number;
	materiaPrima: number;
	minimo: number;
	maximo: number;
	idFornecedor1: number;
	idFornecedor2: number;
	disponivelEntrega: number;
	vlrOferta: number;
	dtInicioOferta: Date;
	dtFimOferta: Date;
	idPlanoContas: number;
	qtdeEmbalagemCompra: number;
	barrasAdicional1: string;
	barrasAdicional2: string;
	vlrGelado: number;
	qtdePromocional: number;
	vlrQtdePromocional: number;
	vlrCxNatural: number;
	vlrCxGelado: number;
	qtdeCx: number;
	vlrPrazo2: number;
	vlrPrazo3: number;
	vlrPrazo4: number;
	vlrPrazo5: number;
	margemVlrPrazo2: number;
	margemVlrPrazo3: number;
	margemVlrPrazo4: number;
	margemVlrPrazo5: number;
	idSubGrupo: number;
	localizacao: string;
	idFamiliaProdutos: number;
	img: string;
	pisCstSaida: string;
	pisCstEntrada: string;
	pisAliqSaida: number;
	cofinsCstSaida: string;
	cofinsCstEntrada: string;
	cofinsAliqSaida: number;
	siglaIcms: string;
	obs: string;
	composicao: string;
	medida: string;
	pesoEmbalagem: number;
	qtdeEmbalagemEtiqueta: string;
	ulFornecedor: string;
	ulCusto: number;
	ulCompra: Date;
	estoque2: number;
	idImpressora: number;
	exibeApp: number;
	adicionais: number;
	qtdeAd: number;
	aplicacao: string;
	percComissao: number;
	vlrFrete: number;
	percReducIcms: number;
	baseLegal: string;
	icmsOrig: string;
	cest: string;
}

type AtributosNovoProduto = Optional<AtributosProduto, "id">

export class Produto extends Model<AtributosProduto, AtributosNovoProduto> {
	declare	id: number;
	declare	barras: string;
	declare	descricao: string;
	declare	unidade: string;
	declare	grupo: number;
	declare	fabricante: number;
	declare	referencia: string;
	declare	vlrCusto: number;
	declare	margemVista: number;
	declare	vlrVista: number;
	declare	margemPrazo: number;
	declare	vlrPrazo: number;
	declare	ncm: string;
	declare	cfopEntradaEstado: string;
	declare	cfopEntradaForaEstado: string;
	declare	cfopSaidaEstado: string;
	declare	cfopSaidaForaEstado: string;
	declare	cst: string;
	declare	percentualIcms: number;
	declare	idBalanca: number;
	declare	validadeBalanca: number;
	declare	idBaixaAlternativa: number;
	declare	qtdeBaixaAlternativa: number;
	declare	status: number;
	declare	dtAlteracao: Date;
	declare	idUsuario: number;
	declare	vlrAtacado: number;
	declare	estoque: number;
	declare	percentualIcmsSt: number;
	declare	materiaPrima: number;
	declare	minimo: number;
	declare	maximo: number;
	declare	idFornecedor1: number;
	declare	idFornecedor2: number;
	declare	disponivelEntrega: number;
	declare	vlrOferta: number;
	declare	dtInicioOferta: Date;
	declare	dtFimOferta: Date;
	declare	idPlanoContas: number;
	declare	qtdeEmbalagemCompra: number;
	declare	barrasAdicional1: string;
	declare	barrasAdicional2: string;
	declare	vlrGelado: number;
	declare	qtdePromocional: number;
	declare	vlrQtdePromocional: number;
	declare	vlrCxNatural: number;
	declare	vlrCxGelado: number;
	declare	qtdeCx: number;
	declare	vlrPrazo2: number;
	declare	vlrPrazo3: number;
	declare	vlrPrazo4: number;
	declare	vlrPrazo5: number;
	declare	margemVlrPrazo2: number;
	declare	margemVlrPrazo3: number;
	declare	margemVlrPrazo4: number;
	declare	margemVlrPrazo5: number;
	declare	idSubGrupo: number;
	declare	localizacao: string;
	declare	idFamiliaProdutos: number;
	declare	img: string;
	declare	pisCstSaida: string;
	declare	pisCstEntrada: string;
	declare	pisAliqSaida: number;
	declare	cofinsCstSaida: string;
	declare	cofinsCstEntrada: string;
	declare	cofinsAliqSaida: number;
	declare	siglaIcms: string;
	declare	obs: string;
	declare	composicao: string;
	declare	medida: string;
	declare	pesoEmbalagem: number;
	declare	qtdeEmbalagemEtiqueta: string;
	declare	ulFornecedor: string;
	declare	ulCusto: number;
	declare	ulCompra: Date;
	declare	estoque2: number;
	declare	idImpressora: number;
	declare	exibeApp: number;
	declare	adicionais: number;
	declare	qtdeAd: number;
	declare	aplicacao: string;
	declare	percComissao: number;
	declare	vlrFrete: number;
	declare	percReducIcms: number;
	declare	baseLegal: string;
	declare	icmsOrig: string;
	declare	cest: string;
}